<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Guard\CPanel\Provider\Identity;

use MSBios\Guard\Provider\Identity\AuthenticationProvider as DefaultAuthenticationProvider;
use MSBios\Guard\Provider\RoleProviderInterface;
use MSBios\Guard\Resource\Entity\Role;
use Zend\Authentication\AuthenticationService;

/**
 * Class AuthenticationProvider
 * @package MSBios\Guard\CPanel\Provider\Identity
 */
class AuthenticationProvider extends DefaultAuthenticationProvider
{
    /** @var AuthenticationService */
    protected $authenticationService;

    /**
     * AuthenticationProvider constructor.
     * @param AuthenticationService $authenticationService
     */
    public function __construct(AuthenticationService $authenticationService)
    {
        $this->authenticationService = $authenticationService;
    }

    /**
     * @return array
     */
    public function getIdentityRoles()
    {
        /** @var RoleProviderInterface $identity */
        $identity = $this->authenticationService->getIdentity();

        // var_dump($identity); die();

        if ($identity instanceof RoleProviderInterface) {

            /** @var array $roles */
            $roles = [];

            /** @var Role $role */
            foreach ($identity->getRoles() as $role) {
                $roles[] = $role->getCode();
            }

            if (empty($roles)) {
                $roles[] = $this->getAuthenticatedRole();
            }

            return $roles;
        }

        return parent::getIdentityRoles(); // TODO: Change the autogenerated stub
    }
}
