<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Guard\CPanel;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>

    <?=
    $this->headTitle($this->translate('MSBios CMS by Judzhin Miles'))
        ->setSeparator(' - ')
        ->setAutoEscape(false);
    ?>

    <?=
    $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no');
    ?>

    <?=
    $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath('simple/assets/images/favicon.ico')])
        ->prependStylesheet($this->basePath('assets/css/colors.css'))
        ->prependStylesheet($this->basePath('assets/css/components.css'))
        ->prependStylesheet($this->basePath('assets/css/core.css'))
        ->prependStylesheet($this->basePath('assets/css/bootstrap.css'))
        ->prependStylesheet($this->basePath('assets/css/icons/icomoon/styles.css'))
        ->prependStylesheet($this->basePath('assets/css/icons/fontawesome/styles.min.css'))
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900');
    ?>

    <?=
    $this->headScript()
        ->prependFile($this->basePath('assets/js/core/app.js'))
        // Core JS Files
        ->prependFile($this->basePath('assets/js/plugins/loaders/blockui.min.js'))
        ->prependFile($this->basePath('assets/js/core/libraries/bootstrap.min.js'))
        ->prependFile($this->basePath('assets/js/core/libraries/jquery.min.js'))
        ->prependFile($this->basePath('assets/js/plugins/loaders/pace.min.js'));
    ?>

</head>

<body class="login-container">

<!-- Main navbar -->
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <a class="navbar-brand" href="<?= $this->url('cpanel'); ?>">
            <img src="<?= $this->basePath('assets/images/logo_light_msbios.png'); ?>" alt="">
        </a>

        <ul class="nav navbar-nav pull-right visible-xs-block">
            <li>
                <a data-toggle="collapse" data-target="#navbar-mobile">
                    <i class="icon-tree5"></i>
                </a>
            </li>
        </ul>
    </div>

</div>
<!-- /main navbar -->

<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div class="content">

                <?= $this->content; ?>

                <!-- Footer -->
                <div class="footer text-muted text-center">
                    &copy; <?= date('Y'); ?>.
                    <a href="#">CPanel</a> by <a href="http://msbios.com" target="_blank">
                        Judzhin Miles
                    </a>
                </div>
                <!-- /footer -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->

</body>
</html>